name: Windows Unittests

on: [push, pull_request]

env:
  GST_REGISTRY: '~/registry.bin'
  KIVY_GL_BACKEND: 'angle_sdl2'
  KIVY_SPLIT_EXAMPLES: 1

jobs:
  unit_test:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ '3.6', '3.7', '3.8' ]
        arch: ['x64', 'x86']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: Install dependencies
      run: |
        . .\.ci\windows_ci.ps1
        Install-kivy-test-run-win-deps
        Install-kivy-test-run-pip-deps
    - name: Install Kivy
      run: |
        . .\.ci\windows_ci.ps1
        [System.Net.WebClient]::new().DownloadFile('https://live.sysinternals.com/procmon.exe' , 'C:\Windows\procmon.exe')
        [System.Net.WebClient]::new().DownloadFile('https://github.com/al-cheb/test/raw/master/procmon.pmc' , 'C:\procmon.pmc')
        procmon.exe /accepteula /backingfile c:\log.pml /quiet

        Install-kivy

        procmon.exe /terminate | Out-Null
        dir C:\
        procmon.exe /Quiet /Minimized /Openlog c:\log.pml /LoadConfig C:\procmon.pmc /SaveApplyFilter /SaveAs C:\pmc.pml | Out-Null
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: procmon
        path: C:\pmc.pml
    - name: Test Kivy
      run: |
        . .\.ci\windows_ci.ps1
        Test-kivy
